version: '3.8'

services:
  # Serviço de Banco de Dados
  db:
    image: eduardogdfrt/oficina:latest
    container_name: db-container
    environment:
      SA_PASSWORD: yourStrong!Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - oficina_network

  # Serviço de Frontend (Node)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - "3000:3000"
    working_dir: /frontend
    volumes:
      - ./front:/frontend
    command: ["npm", "start"]

  # Serviço de Backend (.NET)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    environment:
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_ENVIRONMENT: "Production"
      DefaultConnection: "Server=db-container,1433;Initial Catalog=oficinaDB;User ID=sa;Password=yourStrong!Passw0rd;Encrypt=False;"
    ports:
      - "5000:5000"
    networks:
      - oficina_network

networks:
  oficina_network:
    driver: bridge
