version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ELLP
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Db/backup_ellp.sql:/docker-entrypoint-initdb.d/backup_ellp.sql
    restart: always

  downloader:
    image: alpine:latest
    container_name: downloader
    volumes:
      - ./Db:/Db
    command: >
      sh -c "apk add --no-cache curl && curl -L https://github.com/Eduardogdfrt/Oficina2/raw/main/db/backup_ellp.sql -o /Db/backup_ellp.sql"
    restart: "no"

volumes:
  mysql_data: {}
