sversion: '3.8'

services:
  webapi:
    build:
      context: ./back/entrypoints/WebApplication1/WebApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ELLP
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

