version: '3.8'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
