version: '3.8'

services:
  frontend:
    build:
      context: .             
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"           
    environment:
      - CI=false

  backend:
    build:
      context: .              
      dockerfile: Dockerfile  
    ports:
      - "5000:5000"           
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Production