version: '3.8'

services:
  webapi:
    build:
      context: ./novapasta/back/entrypoint/WebApplication1/WebApi
    container_name: webapi-container
    environment:
      MYSQL_CONNECTION_STRING: "${MYSQL_CONNECTION_STRING}" secrets)
    ports:
      - "5000:80"  
    volumes:
      - ./novapasta/back:/app
    working_dir: /app/entrypoint/WebApplication1/WebApi 
    command: ["dotnet", "WebApi.dll"]  # Comando para rodar a API
    restart: always

  mysql:
    image: mysql:latest
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ELLP
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./novapasta/db/backup_ellp.sql:/docker-entrypoint-initdb.d/backup_ellp.sql
    restart: always

volumes:
  mysql_data: {}
