version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ELLP
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # springboot-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: springboot_app
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ELLP
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: root
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysql

  # react-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.react
  #   container_name: react_app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - springboot-app

volumes:
  mysql_data:
