# Etapa 1: Construção da imagem
FROM node:16 AS build

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o package.json e package-lock.json para o contêiner
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie todo o código fonte da aplicação para o contêiner
COPY . .

# Execute a construção do projeto React
RUN npm run build

# Etapa 2: Servir a aplicação
FROM nginx:alpine

# Copie a build gerada na etapa anterior para o diretório padrão do nginx
COPY --from=build /app/build /usr/share/nginx/html

# Exponha a porta 80 do contêiner (porta do nginx)
EXPOSE 3000

# Comando para rodar o nginx
CMD ["nginx", "-g", "daemon off;"]