# Etapa 1: Construção da imagem
FROM node:16 AS build

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /front

# Copie o package.json e package-lock.json para o contêiner
COPY package*.json /front

# Instale as dependências
RUN npm install

# Copie todo o código fonte da aplicação para o contêiner
COPY . .

# Execute a construção do projeto React
RUN npm run build

# Etapa 2: Servir a aplicação
FROM nginx:alpine

# Copie a build gerada na etapa anterior para o diretório padrão do nginx
COPY --from=build /front/build /usr/share/nginx/html

# Configuração personalizada do nginx (opcional)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponha a porta correta do nginx
EXPOSE 80

# Comando para rodar o nginx
CMD ["nginx", "-g", "daemon off;"]
