name: CI/CD

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'
  pull_request:
    branches:
      - main
      - dev
      - 'feature/*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Choose the branch to deploy'
        required: true
        default: 'main'
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Use a versão do .NET Core que você está utilizando

    - name: Build .NET application
      working-directory: ./novapasta/back/entrypoint/WebApplication1/WebApi
      run: dotnet build --configuration Release

    - name: Run .NET tests
      working-directory: ./novapasta/back/entrypoint/WebApplication1/WebApi
      run: dotnet test --configuration Release

    - name: Publish .NET application
      run: |
        dotnet publish ./novapasta/back/entrypoint/WebApplication1/WebApi -c Release -o ./publish

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}  # Nome do seu Azure Web App
        package: './publish'  # Diretório de saída do .NET Publish
