jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}

    - name: Clean up existing containerd packages
      run: |
        sudo apt-get remove -y containerd containerd.io
        sudo apt-get autoremove -y
        sudo apt-get clean

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build .NET application
      working-directory: ./Back
      run: dotnet build --configuration Release

    - name: Run .NET tests
      working-directory: ./Back
      run: dotnet test --configuration Release

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}

    - name: Clean up existing containerd packages
      run: |
        sudo apt-get remove -y containerd containerd.io
        sudo apt-get autoremove -y
        sudo apt-get clean

    - name: Build Docker image
      run: docker build -t myapp-webapi ../Back/entrypoint/WebApi

    - name: Publish Docker image to Azure Container Registry (ACR)
      run: |
        docker tag myapp-webapi:latest myregistry.azurecr.io/myapp-webapi:latest
        docker push myregistry.azurecr.io/myapp-webapi:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "my-azure-app"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./Back/entrypoint/WebApi
        connection-string: ${{ secrets.SQL_SERVER_SECRET }}

    - name: Clean up
      run: docker system prune -af
