name: Deploy Backend to Hml

on:
  push:
    branches:
      - release
      - Feature/Fabio
    paths:
      - 'Back/**'
      - '.github/workflows/deploy-backend-hml.yml'

jobs:
  deploy-backend-to-hml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore .NET dependencies
        run: |
          echo "Restoring .NET dependencies..."
          dotnet restore Back/WebApia/

      - name: Build .NET project
        run: |
          echo "Building .NET project..."
          dotnet build Back/WebApia/ --configuration release

      - name: Verify project structure
        run: |
          echo "Verifying project structure..."
          ls -R Back/
          if [ ! -f "Back/Dockerfile" ]; then
            echo "ERROR: Dockerfile not found in Back directory"
            exit 1
          fi

      - name: Build and Push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Back
          file: ./Back/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/central-oficina2:hml
          cache-from: type=registry,ref=${{ secrets.ACR_LOGIN_SERVER }}/central-oficina2:hml
          cache-to: type=inline

      - name: Verify Backend App Service exists
        run: |
          echo "Verifying App Service exists..."
          if ! az webapp show --name centralOficina2-Hml --resource-group CentralOficina2-Hml &>/dev/null; then
            echo "App Service 'centralOficina2-Hml' not found. Creating it..."
            az webapp create \
              --name centralOficina2-Hml \
              --resource-group CentralOficina2-Hml \
              --plan CentralOficina2Plan \
              --runtime "DOCKER"
          fi

      - name: Configure Backend App Service
        run: |
          echo "Configuring Backend App Service..."
          az webapp config container set \
            --name centralOficina2-Hml \
            --resource-group CentralOficina2-Hml \
            --container-image-name ${{ secrets.ACR_LOGIN_SERVER }}/central-oficina2:hml \
            --container-registry-url https://${{ secrets.ACR_LOGIN_SERVER }} \
            --container-registry-user ${{ secrets.ACR_USERNAME }} \
            --container-registry-password ${{ secrets.ACR_PASSWORD }}

      - name: Restart Backend App Service
        run: |
          echo "Restarting Backend App Service..."
          az webapp restart --name centralOficina2-Hml --resource-group CentralOficina2-Hml

      - name: Validate Backend Deployment
        run: |
          echo "Validating backend deployment..."
          backend_status=$(az webapp show --name centralOficina2-Hml --resource-group CentralOficina2-Hml --query state -o tsv)
          echo "Backend Deployment Status: $backend_status"
          if [ "$backend_status" != "Running" ]; then
            echo "WARNING: Backend App Service is not in Running state"
            exit 1
          fi

      - name: Deployment Summary
        run: |
          echo "Backend Deployment Summary:"
          echo "- Image: ${{ secrets.ACR_LOGIN_SERVER }}/central-oficina2:hml"
          echo "- App Service: centralOficina2-Hml"
          echo "- Resource Group: CentralOficina2-Hml"
          echo "Status: Success"