name: Deploy to Dev Environment with ACR

on:
  push:
    branches:
        -Feature/*
      - Release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Login no Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Login no ACR
    - name: Log in to ACR
      run: |
        az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}

    # Build da imagem do backend
    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/centraloficina2-backend:dev ./Central-oficina2/Back/WebApia
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/centraloficina2-backend:dev

    # Build da imagem do frontend
    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/centraloficina2-frontend:dev ./Central-oficina2/front
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/centraloficina2-frontend:dev

    # Deploy no App Service
    - name: Deploy Backend to App Service
      run: |
        az webapp config container set \
          --name CentralOficina2-Dev \
          --resource-group CentralOficina2-Dev \
          --docker-custom-image-name ${{ secrets.ACR_LOGIN_SERVER }}/centraloficina2-backend:dev \
          --docker-registry-server-url https://${{ secrets.ACR_LOGIN_SERVER }} \
          --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
          --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

    - name: Deploy Frontend to App Service
      run: |
        az webapp config container set \
          --name CentralOficina2-Dev \
          --resource-group CentralOficina2-Dev \
          --docker-custom-image-name ${{ secrets.ACR_LOGIN_SERVER }}/centraloficina2-frontend:dev \
          --docker-registry-server-url https://${{ secrets.ACR_LOGIN_SERVER }} \
          --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
          --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}
