name: Deploy to Hml on Release Changes

on:
  push:
    branches:
      - release  # Alterado para a branch 'release', ajuste conforme necessário
    paths:
      - 'Back/**'
      - 'front/**'
      - '.github/workflows/deploy-hml.yml'
      - 'docker-compose.yml'

jobs:
  deploy-to-hml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: centraloficina2acr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Clean Up Old Images and Containers
        run: |
          echo "Removing old images and containers..."
          docker ps -a -q | xargs -r docker rm -f || true
          docker images -q | xargs -r docker rmi -f || true
          docker system prune -f --volumes

      - name: Build and Push Image
        run: |
          docker build -t centraloficina2acr.azurecr.io/centraloficina2:latest . --no-cache
          docker tag centraloficina2 centraloficina2acr.azurecr.io/centraloficina2:latest
          docker push centraloficina2acr.azurecr.io/centraloficina2:latest

      - name: Configure App Service
        run: |
            az webapp config container set \
              --name centraloficina2 \
              --resource-group centraloficina2rg \
              --container-image-name centraloficina2acr.azurecr.io/centraloficina2:$VERSION_TAG \
              --container-registry-url https://centraloficina2acr.azurecr.io \
              --container-registry-user ${{ secrets.ACR_USERNAME }} \
              --container-registry-password ${{ secrets.ACR_PASSWORD }} \
              --env PORT=3000  # Configura a variável de ambiente PORT corretamente para o container
            echo "Updated Azure Web App to use image with tag: $VERSION_TAG"
        

      - name: Restart App Service
        run: |
          az webapp restart --name centraloficina2 --resource-group centraloficina2rg
          echo "App Service restarted."

      - name: Validate Deployments
        run: |
          max_retries=10
          sleep_time=15
          retries=0
          while [ "$(az webapp show --name centralOficina2-Hml --resource-group CentralOficina2-Hml --query state -o tsv)" != "Running" ]; do
            echo "Waiting for App Service to be in Running state..."
            sleep $sleep_time
            retries=$((retries + 1))
            if [ "$retries" -ge "$max_retries" ]; then
              echo "App Service did not reach Running state within expected time."
              exit 1
            fi
          done
          echo "App Service is now running."
