name: Deploy Database

on:
  push:
    branches:
      - Release # Dispara apenas para mudanças na branch Release
    paths:
      - 'db/**' # Dispara apenas para mudanças na pasta db

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push DB Docker Image
        run: |
          az acr login --name centraloficina2acr
          docker build -t centraloficina2acr.azurecr.io/centraloficina2-db:${{ github.sha }} -f ./db/Dockerfile .
          docker push centraloficina2acr.azurecr.io/centraloficina2-db:${{ github.sha }}

      - name: Deploy to App Service
        run: |
          az webapp config container set \
            --name CentralOficina2-Dev \
            --resource-group CentralOficina2-Dev \
            --docker-custom-image-name centraloficina2acr.azurecr.io/centraloficina2-db:${{ github.sha }}
