name: Deploy to Hml on Release Changes

on:
  push:
    branches:
      - release
    paths:
      - 'Back/**'
      - 'docker-compose.yml'
      - '.github/workflows/deploy-hml.yml'

jobs:
  deploy-to-hml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: centraloficina2acr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Backend
        run: |
          docker-compose build back
          docker-compose push back

      - name: Configure App Service
        run: |
          az webapp config container set \
            --name centralOficina2-Hml \
            --resource-group CentralOficina2-Hml \
            --container-image-name centraloficina2acr.azurecr.io/central-oficina2:hml \
            --container-registry-url https://centraloficina2acr.azurecr.io \
            --container-registry-user ${{ secrets.ACR_USERNAME }} \
            --container-registry-password ${{ secrets.ACR_PASSWORD }}

      - name: Restart App Service
        run: |
          az webapp restart --name centralOficina2-Hml --resource-group CentralOficina2-Hml
